### ISSUE TITLE
Repo for u_lift_u

### ISSUE THREAD

**Issue by mariekers** [CodeForPhilly/ops#41]
- [x] **Link to project profile**: https://codeforphilly.org/projects/uliftu_website_redesign
- [x] **Desired repository name**: https://github.com/CodeForPhilly/uliftu-site
  - *We recommend the [monorepo pattern](https://gomonorepo.org/) be employed if possible*
  - *Repository names should be all-lower, [kebab-case](https://en.toolpage.org/tool/kebabcase)*
- [x] **GitHub users who should have admin access**:
  - @mariekers
- [x] **GitHub users who should have write access**:
  - @mariekers

**Comment by themightychris** [comment]
@mariekers all set: https://github.com/CodeForPhilly/uliftu-site

I just added another question to the template for this issue to choose a license for the new repository. In the meantime, I did not apply any license to the new repository. I recommend using the `MIT` license as a default choice though, which enables everyone to reuse any code without restriction. This is a good idea I think because it assures to all potential contributors that whatever code snippets they develop/repurpose for this project can be freely reused in any other project, public or personal. Attaching an MIT license to the code *does not* grant anyone the right to replicate the organizations name/branding -- that's covered by trademark law separately from the copyrights on written/borrowed code that the license addresses.
